# Generated by Django 4.2.4 on 2023-10-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
    ]
